vkdev="/www/verkkokauppacom/dev"
alias cdd="cd $vkdev"
alias pu="phpunit --colors --verbose"
alias puc="phpunit --colors --verbose --coverage-clover /Volumes/verkkokauppacom-code/verkkokauppacom/tmp/phpunit-clover.xml --coverage-html /Volumes/verkkokauppacom-code/verkkokauppacom/tmp/phpunit-coverage"
alias ppu="parallel-phpunit --pu-cmd phpunit --colors --verbose"
